### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by simenandre** [bjerkio/vault-action#124]
Hi!

**USERS BEWARE**

This action naively outputs secrets from Vault using regular `setOutput` functions resulting in secrets being displayed in logs. @actions/core features `setSecret` where outputs are masked in logs.

Potential fix:
--> Replace all setOutput with setSecret.

```javascript
core.setSecret('myPassword');
```

**Comment by maanuanubhav999** [comment]
@cobraz hello, I would like to help.

**Comment by simenandre** [comment]
Thank you! Id appreciate a pull request :)

**Comment by simenandre** [comment]
@maanuanubhav999 Do you know when you’ll have time to fix it? You see, since this is a security issue I really would like to get it posted before EOD Wednesday (CEST) at the latest.

**Comment by maanuanubhav999** [comment]
@cobraz sorry, I am trying to figure the installation can you just guide a little.

**Comment by cobraz** [comment]
Okey :)

**Comment by simenandre** [comment]
Okey :)

Most of the files for this repository is found under `src/`. `main.ts` is just referencing other files, so ignore that. In `getVaultSecret.ts`, you'll find the actual functionality that gets our Vault Secrets. However, I've made another file where we have our output functions, relevant for this issue (`transformOutput.ts`).

```typescript
export const outputData = (name: string, value: string): void => {
  /**
   * @todo Add so that environment variables are exported
   * @body Currently it only setOutputs and debugs all outputs
   */
  setOutput(name || 'secret', value);
  debug(`✔ ${name} => outputs.${name}`);
};
```

This is where we output. We should no longer use `setOutput`, but `setSecret`.
